### ISSUE TITLE
A problem about the carb

### ISSUE THREAD

**Issue by lioninline** [youngbin-ro/Multi2OIE#2]
hello, I meet a problem about the carb. The error info is following. Thanks for your help!

```
/code/XXX/miniconda3/envs/multi2oie/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.preprocessing.data module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  warnings.warn(message, FutureWarning)
[nltk_data] Error loading wordnet: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from test import do_eval
  File "/home/wurui/spacy_ie/Multi2OIE-master/test.py", line 13, in <module>
    from carb.tabReader import TabReader
ModuleNotFoundError: No module named 'carb.tabReader'

If you suspect this is an IPython 7.14.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by juanma1982** [comment]
same error

**Comment by HLasse** [comment]
Fixed it by moving tabReader.py into the carb directory instead of carb/oie_readers

**Comment by youngbin-ro** [comment]
I apologize for the late reply. The https://github.com/youngbin-ro/Multi2OIE/issues/2#issuecomment-842205871 is correct answer.
The issue is closed because the problem is solved by the commit https://github.com/youngbin-ro/Multi2OIE/commit/de3df55dcfdcc3844fc0567e2ba26057a49a37d1.
